disabled_rules:
  - function_parameter_count
  - line_length
  - function_body_length
  - type_body_length
  - file_length
  - vertical_whitespace
  - cyclomatic_complexity
  - statement_position
  - closure_parameter_position
  - orphaned_doc_comment

opt_in_rules:
  - file_types_order
  - overridden_super_call
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - contains_over_filter_count
  - first_where
  - last_where
  - empty_collection_literal
  - empty_count
  - empty_string
  - convenience_type
  - closure_spacing
  - file_name
  - flatmap_over_map_reduce
  - legacy_multiple
  - operator_usage_whitespace
  - redundant_type_annotation

custom_rules:
  print:
    included: ".*\\.swift"
    name: "Print"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Prints should be removed"
    severity: warning

excluded:
  - Snapshot/SnapshotHelper.swift
  - Shared/Generated

identifier_name:
  excluded:
    - id

trailing_whitespace:
  ignores_empty_lines: true

large_tuple:
  warning: 3
  error: 4
