default_platform(:ios)

skip_docs
opt_out_usage

lane :bump_version do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: "develop")
    increment_build_number_in_xcodeproj(target: "Passwords")
    increment_build_number_in_xcodeproj(target: "Provider")
    increment_build_number_in_xcodeproj(target: "Extension")
    increment_version_number_in_xcodeproj(bump_type: options[:bump_type], target: "Passwords")
    increment_version_number_in_xcodeproj(bump_type: options[:bump_type], target: "Provider")
    increment_version_number_in_xcodeproj(bump_type: options[:bump_type], target: "Extension")
    commit_version_bump(message: "Bump version")
end
