scheme("Snapshot")
clear_previous_screenshots(true)
override_status_bar(true)
number_of_retries(0)

devices([
    "iPhone 13 Pro Max",
    "iPhone 13 Pro",
    "iPhone 8 Plus",
    "iPhone SE (3rd generation)",
    "iPhone SE (1st generation)",
    "iPad Pro (12.9-inch) (5th generation)",
    "iPad Pro (12.9-inch) (2nd generation)",
    "iPad Pro (11-inch) (3rd generation)",
    "iPad Air (3rd generation)",
    "iPad (6th generation)"
])

languages([
    "en-US",
    "de-DE"
])
